<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><Compile Remove="Contracts\**\*.cs" /></ItemGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.18.6" />
    <PackageReference Include="FastEndpoints" Version="7.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\core\Palladin.Core.Api\Palladin.Core.Api.csproj" />
    <ProjectReference Include="..\..\core\Palladin.Core.Events\Palladin.Core.Events.csproj" />
    <ProjectReference Include="..\..\core\Palladin.Core.Guid\Palladin.Core.Guid.csproj" />
    <ProjectReference Include="..\..\core\Palladin.Core.MassTransit\Palladin.Core.MassTransit.csproj" />
    <ProjectReference Include="..\..\core\Palladin.Core.Persistence\Palladin.Core.Persistence.csproj" />
    <ProjectReference Include="..\..\core\Palladin.Core.Security\Palladin.Core.Security.csproj" />
    <ProjectReference Include="..\..\core\Palladin.Core.Types\Palladin.Core.Types.csproj" />
    <ProjectReference Include="Contracts\Palladin.Module.PublicAssetCatalog.Contracts.csproj" />
  </ItemGroup>
</Project>
