// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palladin.Module.PublicAssetCatalog.Infrastructure.Persistence;

#nullable disable

namespace Palladin.Module.PublicAssetCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PublicAssetCatalogDbWriteContext))]
    [Migration("20260806194616_TrackWebsiteIconAcquisitionScheduling")]
    partial class TrackWebsiteIconAcquisitionScheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("AcquisitionScheduledAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentRevision")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Type", "OwnerId")
                        .IsUnique();

                    b.HasIndex("Type", "Status", "Name");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAssetAlias", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.HasKey("AssetId", "Kind", "Value");

                    b.HasIndex("Kind", "Value")
                        .IsUnique()
                        .HasFilter("\"Kind\" = 1");

                    b.ToTable("PublicAssetAlias");
                });

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAssetRevision", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("AssetId", "Revision");

                    b.HasIndex("Digest");

                    b.ToTable("PublicAssetRevision");
                });

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAssetUploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpectedByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpectedDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExpectedMediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceSubject")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StagingKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId", "ExpiresAt");

                    b.ToTable("UploadSessions");
                });

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAssetAlias", b =>
                {
                    b.HasOne("Palladin.Module.PublicAssetCatalog.Domain.PublicAsset", null)
                        .WithMany("Aliases")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAssetRevision", b =>
                {
                    b.HasOne("Palladin.Module.PublicAssetCatalog.Domain.PublicAsset", null)
                        .WithMany("Revisions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.PublicAssetCatalog.Domain.PublicAsset", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
