<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FastEndpoints" Version="7.2.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Palladin.Core.Api\Palladin.Core.Api.csproj" />
    </ItemGroup>

</Project>
