// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palladin.Module.Notification.Infrastructure.Persistence;

#nullable disable

namespace Palladin.Module.Notification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbWriteContext))]
    partial class NotificationDbWriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palladin.Module.Notification.Domain.EmailDelivery", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("EmailDeliveries");
                });

            modelBuilder.Entity("Palladin.Module.Notification.Domain.InboxItem", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<bool>("Collapsible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RequiredPermission")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScopeItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "UserId", "Id");

                    b.HasIndex("OrganizationId", "SubjectId");

                    b.HasIndex("OrganizationId", "Type", "SubjectId");

                    b.HasIndex("OrganizationId", "UserId", "OccurredAt", "Id")
                        .IsDescending(false, false, true, true);

                    b.HasIndex("OrganizationId", "UserId", "ScopeType", "ScopeItemId");

                    b.HasIndex("OrganizationId", "UserId", "Type", "SubjectId")
                        .IsUnique();

                    b.HasIndex(new[] { "OrganizationId", "UserId" }, "IX_InboxItems_OrganizationId_UserId_Permission")
                        .HasFilter("\"RequiredPermission\" IS NOT NULL");

                    b.HasIndex(new[] { "OrganizationId", "UserId" }, "IX_InboxItems_OrganizationId_UserId_Unread")
                        .HasFilter("\"ReadAt\" IS NULL");

                    b.ToTable("InboxItems");
                });

            modelBuilder.Entity("Palladin.Module.Notification.Domain.NotificationPreference", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<bool>("InboxEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SignalREnabled")
                        .HasColumnType("boolean");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "UserId", "Type");

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("Palladin.Module.Notification.Domain.PushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PushTokens");
                });

            modelBuilder.Entity("Palladin.Module.Notification.Domain.Scope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "UserId", "Type", "ItemId");

                    b.HasIndex("OrganizationId", "Type", "ItemId");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("Palladin.Module.Notification.Domain.SuppressedEmail", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.HasKey("Address");

                    b.ToTable("SuppressedEmails");
                });

            modelBuilder.Entity("Palladin.Module.Notification.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
