// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palladin.Module.Vault.Infrastructure.Persistence;

#nullable disable

namespace Palladin.Module.Vault.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VaultDbWriteContext))]
    partial class VaultDbWriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palladin.Module.Vault.Domain.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccessEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Instant?>("AccessEpochStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconColor")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IconKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant?>("LastProcessedDeactivationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastProcessedDeactivationEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<decimal>("MutationVersion")
                        .IsConcurrencyToken()
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("RecipientKeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<string>("SigningPublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.AgentVaultDiscoveryEnvelope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AgentEd25519Fingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("AgentMessageKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<byte[]>("AgentWrappedVdk")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AgentWrappedVdkDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AgentX25519Fingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("CryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Instant>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ManifestRevision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte[]>("ManifestSignature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<decimal>("ManifestSigningKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int>("MinimumAgentRuntimeProtocol")
                        .HasColumnType("integer");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ProvisionedAccessEpoch")
                        .HasColumnType("bigint");

                    b.Property<Instant>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProvisionedBy")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RecipientAgentKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("RecipientAgentKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("VaultAgentMessageKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("VaultAgentMessagePublicKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("VaultSigningKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("VaultSigningPublicKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("VdkVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("WrapperSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrganizationId", "VaultId", "AgentId");

                    b.HasIndex("OrganizationId", "AgentId");

                    b.ToTable("AgentVaultDiscoveryEnvelope", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.AgentWrappedVaultKey", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<long>("AgentAccessEpoch")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("EncodedSealedVaultKeyPackage")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ProducerSignature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RecipientAgentKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("RecipientAgentKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("VaultKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<byte[]>("VaultSigningKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("VaultSigningKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("WrapperSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrganizationId", "VaultId", "GrantId");

                    b.HasIndex("OrganizationId", "VaultId", "AgentId")
                        .IsUnique();

                    b.ToTable("AgentWrappedVaultKeys", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.CredentialFailureReport", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "AgentId", "VaultId", "EntryId", "Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.HasIndex("OrganizationId", "EntryId");

                    b.ToTable("CredentialFailureReports");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.EncryptedPresentationAsset", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CiphertextLength")
                        .HasColumnType("integer");

                    b.Property<byte[]>("CiphertextSha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<short>("Target")
                        .HasColumnType("smallint");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "VaultId", "Id");

                    b.HasIndex("StorageId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "VaultId", "EntryId");

                    b.ToTable("EncryptedPresentationAssets", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.EncryptedReasonEnvelope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<long>("AgentMessageKeyVersion")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("AgentMessageWrappedReasonDek")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AgentSignature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<string>("CryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("EncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(4120)
                        .HasColumnType("bytea");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<long>("MemberKeyGeneration")
                        .HasColumnType("bigint");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<long>("ReasonKeyVersion")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RecipientAgentMessageKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<int>("RequestedMethods")
                        .HasColumnType("integer");

                    b.Property<decimal>("ResourceRevision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("WrapperSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrganizationId", "VaultId", "GrantRequestId");

                    b.HasIndex("OrganizationId", "VaultId", "EntryId");

                    b.ToTable("EncryptedReasonEnvelopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.EntryCreationChallenge", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ConsumedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "VaultId", "EntryId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OrganizationId", "VaultId", "RequestedBy");

                    b.ToTable("EntryCreationChallenges");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.Grant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AgentAccessEpoch")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentPublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("DeniedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeniedBy")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpirySource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("LastAccessHostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("LastAccessIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Instant?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Methods")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("QueryCount")
                        .HasColumnType("integer");

                    b.Property<int?>("QueryLimit")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestType")
                        .HasColumnType("integer");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("RevokedBySystem")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Instant?>("SupersededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersededByGrantId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Status");

                    b.HasIndex("VaultId", "Status");

                    b.HasIndex("AgentId", "AgentAccessEpoch", "Status");

                    b.HasIndex("VaultId", "CreatedAt", "Id");

                    b.HasIndex("OrganizationId", "AgentId", "CreatedAt", "Id");

                    b.HasIndex("OrganizationId", "Status", "CreatedAt", "Id");

                    b.HasIndex("OrganizationId", "VaultId", "CreatedAt", "Id");

                    b.ToTable("Grants");

                    b.HasDiscriminator<string>("GrantType").HasValue("Grant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.GrantEntryEnvelope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AgentKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AgentWrappedGrantDek")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("bytea");

                    b.Property<string>("CryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("EncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(262168)
                        .HasColumnType("bytea");

                    b.Property<decimal>("EntryRevision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Instant?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrantEnvelopeRevision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("GrantKeyVersion")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("RecipientAgentKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int?>("RemainingUses")
                        .HasColumnType("integer");

                    b.Property<string>("WrapperSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrganizationId", "VaultId", "GrantId", "EntryId");

                    b.ToTable("GrantEntryEnvelopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.GrantEntryScope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeliveryPolicy")
                        .HasColumnType("integer");

                    b.Property<string>("FieldIds")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.Property<int>("Methods")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "VaultId", "GrantId", "EntryId");

                    b.HasIndex("OrganizationId", "VaultId", "EntryId");

                    b.ToTable("GrantEntryScopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.MemberKeyDirectoryEntry", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("KeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("MemberKeyDirectory");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.ScriptExecutionPackage", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<long>("AgentAccessEpoch")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("EncodedPackageCiphertext")
                        .IsRequired()
                        .HasMaxLength(2097152)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ManifestDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("PackageRevision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte[]>("ProducerSignature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecipientAgentKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long>("RecipientAgentKeyVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ScriptEntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ScriptRevision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte[]>("VaultSigningKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long>("VaultSigningKeyVersion")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId", "VaultId", "GrantId");

                    b.ToTable("ScriptExecutionPackages");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.ScriptExecutionScope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("EntryRevision")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsScript")
                        .HasColumnType("boolean");

                    b.HasKey("OrganizationId", "VaultId", "GrantId", "EntryId");

                    b.HasIndex("OrganizationId", "VaultId", "EntryId", "GrantId");

                    b.ToTable("ScriptExecutionScopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.Vault", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AgentMessageKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AgentMessagePublicKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentAgentMessageKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CurrentManifestSigningKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CurrentVaultKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CurrentVdkVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<Instant?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletionRequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletionRequestedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("DiscoverySequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleting")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("ManifestSigningKeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ManifestSigningPublicKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<decimal>("MemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("MemberSequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("MemberVaultMetadataCryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("MemberVaultMetadataEncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(16408)
                        .HasColumnType("bytea");

                    b.Property<decimal>("MemberVaultMetadataKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("MetadataRevision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MinRetainedDiscoverySequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MinRetainedMemberSequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MutationVersion")
                        .IsConcurrencyToken()
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("CreatedBy")
                        .IsUnique()
                        .HasFilter("\"IsDefault\"");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultCreationChallenge", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ConsumedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "VaultId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OrganizationId", "RequestedBy")
                        .IsUnique();

                    b.ToTable("VaultCreationChallenges");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentDiscoveryCryptoSuiteId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("AgentDiscoveryEncodedSuitePayload")
                        .HasMaxLength(16408)
                        .HasColumnType("bytea");

                    b.Property<decimal?>("AgentDiscoveryMemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int?>("AgentDiscoveryProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AgentDiscoveryRevision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("AgentDiscoveryRevisionHighWatermark")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AgentDiscoveryVdkVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<Instant?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CurrentRevision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DeliveryPolicy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPurging")
                        .HasColumnType("boolean");

                    b.Property<string>("MemberIndexCryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("MemberIndexEncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(32792)
                        .HasColumnType("bytea");

                    b.Property<decimal>("MemberIndexMemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int>("MemberIndexProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("MemberIndexRevision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("PurgeLedgerRequired")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("PurgeRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PurgeRequestedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "VaultId", "Id");

                    b.HasIndex("OrganizationId", "VaultId", "CreatedAt", "Id");

                    b.ToTable("VaultEntries", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntryKey", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("KeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("CryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("EncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("bytea");

                    b.Property<decimal>("MemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<decimal>("WrapperRevision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WrappingKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.HasKey("OrganizationId", "VaultId", "EntryId", "KeyVersion");

                    b.ToTable("VaultEntryKeys", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntryVersion", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Revision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<Instant>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uuid");

                    b.Property<int>("ChangedByType")
                        .HasColumnType("integer");

                    b.Property<string>("CryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("DiscoverySequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("KeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<bool>("MemberIndexChanged")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<byte[]>("MemberSecretEncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(262168)
                        .HasColumnType("bytea");

                    b.Property<decimal>("MemberSequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "VaultId", "EntryId", "Revision");

                    b.HasIndex("OrganizationId", "VaultId", "DiscoverySequence")
                        .IsUnique()
                        .HasFilter("\"DiscoverySequence\" IS NOT NULL");

                    b.HasIndex("OrganizationId", "VaultId", "MemberSequence")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "VaultId", "EntryId", "KeyVersion");

                    b.ToTable("VaultEntryVersions", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyMaterialEnvelope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("CryptoSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("EncodedSuitePayload")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("bytea");

                    b.Property<decimal>("KeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("MemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("Revision")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WrappingKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.HasKey("OrganizationId", "VaultId", "Kind");

                    b.ToTable("VaultKeyMaterialEnvelopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyRotation", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseDiscoverySequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("BaseMemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("BaseMemberSequence")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Cause")
                        .HasColumnType("integer");

                    b.Property<Instant?>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeprovisioningId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExcludedAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExcludedMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FencingToken")
                        .HasColumnType("uuid");

                    b.Property<string>("LastFailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Instant?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseOwnerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LeaseRevision")
                        .IsConcurrencyToken()
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetMemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<Instant>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TriggeredBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "VaultId", "Id");

                    b.HasIndex("OrganizationId", "DeprovisioningId");

                    b.HasIndex("OrganizationId", "VaultId")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 4");

                    b.ToTable("VaultKeyRotations");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyRotationPreparedItem", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RotationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SubjectVersion")
                        .HasColumnType("numeric(20,0)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasMaxLength(524288)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PayloadDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Instant>("PreparedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SourceRevision")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("OrganizationId", "VaultId", "RotationId", "Kind", "SubjectId", "SubjectVersion");

                    b.HasIndex("OrganizationId", "VaultId", "RotationId", "Kind");

                    b.ToTable("VaultKeyRotationPreparedItems");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultMember", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "VaultId", "UserId");

                    b.ToTable("VaultMembers");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultMemberKeyEnvelope", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MemberKeyGeneration")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RecipientKeyFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("RecipientKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<byte[]>("SealedVaultKeyPackage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("VaultKeyVersion")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("WrapperSuiteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrganizationId", "VaultId", "MemberId", "MemberKeyGeneration");

                    b.ToTable("VaultMemberKeyEnvelopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultOrganizationLifecycle", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("MutationVersion")
                        .IsConcurrencyToken()
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("OrganizationId");

                    b.ToTable("VaultOrganizationLifecycles");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultPresentationAssetCutoverState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Instant?>("LegacyObjectsPurgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VaultPresentationAssetCutoverStates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "zero-knowledge-assets"
                        });
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultPrincipalDeprovisioning", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CompletedVaultCount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CurrentRotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentVaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int>("PrincipalType")
                        .HasColumnType("integer");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 2");

                    b.HasIndex("OrganizationId", "PrincipalType", "PrincipalId")
                        .IsUnique()
                        .HasFilter("\"Status\" <> 4");

                    b.HasIndex("OrganizationId", "RequestedAt", "Id");

                    b.ToTable("VaultPrincipalDeprovisionings");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.FullGrant", b =>
                {
                    b.HasBaseType("Palladin.Module.Vault.Domain.Grant");

                    b.HasDiscriminator().HasValue("Full");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.GranularGrant", b =>
                {
                    b.HasBaseType("Palladin.Module.Vault.Domain.Grant");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.HasIndex("EntryId", "OrganizationId", "CreatedAt", "Id")
                        .HasFilter("\"EntryId\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("Granular");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.ScriptExecutionGrant", b =>
                {
                    b.HasBaseType("Palladin.Module.Vault.Domain.Grant");

                    b.Property<Guid>("ScriptEntryId")
                        .HasColumnType("uuid");

                    b.HasIndex("OrganizationId", "VaultId", "ScriptEntryId", "AgentId", "AgentAccessEpoch", "Status")
                        .IsUnique()
                        .HasFilter("\"GrantType\" = 'ScriptExecution' AND \"Status\" = 2");

                    b.HasIndex(new[] { "OrganizationId", "VaultId", "ScriptEntryId", "AgentId", "AgentAccessEpoch", "Status" }, "IX_Grants_ScriptExecution_Pending")
                        .IsUnique()
                        .HasFilter("\"GrantType\" = 'ScriptExecution' AND \"Status\" = 1");

                    b.HasDiscriminator().HasValue("ScriptExecution");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.AgentVaultDiscoveryEnvelope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Agent", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AgentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany("AgentVaultDiscoveryEnvelopes")
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.AgentWrappedVaultKey", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Grant", null)
                        .WithOne("AgentWrappedVaultKey")
                        .HasForeignKey("Palladin.Module.Vault.Domain.AgentWrappedVaultKey", "OrganizationId", "VaultId", "GrantId")
                        .HasPrincipalKey("Palladin.Module.Vault.Domain.Grant", "OrganizationId", "VaultId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.CredentialFailureReport", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.EncryptedPresentationAsset", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Vault.Domain.VaultEntry", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.EncryptedReasonEnvelope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Grant", null)
                        .WithOne("EncryptedReason")
                        .HasForeignKey("Palladin.Module.Vault.Domain.EncryptedReasonEnvelope", "OrganizationId", "VaultId", "GrantRequestId")
                        .HasPrincipalKey("Palladin.Module.Vault.Domain.Grant", "OrganizationId", "VaultId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.EntryCreationChallenge", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.Grant", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany()
                        .HasForeignKey("VaultId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Vault.Domain.Agent", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AgentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.GrantEntryEnvelope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.GrantEntryScope", null)
                        .WithOne("Envelope")
                        .HasForeignKey("Palladin.Module.Vault.Domain.GrantEntryEnvelope", "OrganizationId", "VaultId", "GrantId", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.GrantEntryScope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.VaultEntry", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId", "EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Vault.Domain.Grant", null)
                        .WithMany("GrantEntryScopes")
                        .HasForeignKey("OrganizationId", "VaultId", "GrantId")
                        .HasPrincipalKey("OrganizationId", "VaultId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.ScriptExecutionPackage", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Grant", null)
                        .WithOne("ScriptExecutionPackage")
                        .HasForeignKey("Palladin.Module.Vault.Domain.ScriptExecutionPackage", "OrganizationId", "VaultId", "GrantId")
                        .HasPrincipalKey("Palladin.Module.Vault.Domain.Grant", "OrganizationId", "VaultId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.ScriptExecutionScope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.VaultEntry", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId", "EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Vault.Domain.Grant", null)
                        .WithMany("ScriptExecutionScopes")
                        .HasForeignKey("OrganizationId", "VaultId", "GrantId")
                        .HasPrincipalKey("OrganizationId", "VaultId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntry", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntryKey", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.VaultEntry", null)
                        .WithMany("Keys")
                        .HasForeignKey("OrganizationId", "VaultId", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntryVersion", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.VaultEntry", null)
                        .WithMany("Versions")
                        .HasForeignKey("OrganizationId", "VaultId", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Vault.Domain.VaultEntryKey", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId", "EntryId", "KeyVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyMaterialEnvelope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany("KeyMaterialEnvelopes")
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyRotation", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.VaultPrincipalDeprovisioning", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "DeprovisioningId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Palladin.Module.Vault.Domain.Vault", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Palladin.Module.Vault.Domain.VaultKeyEpoch", "BaseKeyEpoch", b1 =>
                        {
                            b1.Property<Guid>("VaultKeyRotationOrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VaultKeyRotationVaultId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VaultKeyRotationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AgentMessageKeyVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.Property<decimal>("ManifestSigningKeyVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.Property<decimal>("VaultKeyVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.Property<decimal>("VdkVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.HasKey("VaultKeyRotationOrganizationId", "VaultKeyRotationVaultId", "VaultKeyRotationId");

                            b1.ToTable("VaultKeyRotations");

                            b1.WithOwner()
                                .HasForeignKey("VaultKeyRotationOrganizationId", "VaultKeyRotationVaultId", "VaultKeyRotationId");
                        });

                    b.OwnsOne("Palladin.Module.Vault.Domain.VaultKeyEpoch", "TargetKeyEpoch", b1 =>
                        {
                            b1.Property<Guid>("VaultKeyRotationOrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VaultKeyRotationVaultId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VaultKeyRotationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("AgentMessageKeyVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.Property<decimal>("ManifestSigningKeyVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.Property<decimal>("VaultKeyVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.Property<decimal>("VdkVersion")
                                .HasPrecision(10)
                                .HasColumnType("numeric(10,0)");

                            b1.HasKey("VaultKeyRotationOrganizationId", "VaultKeyRotationVaultId", "VaultKeyRotationId");

                            b1.ToTable("VaultKeyRotations");

                            b1.WithOwner()
                                .HasForeignKey("VaultKeyRotationOrganizationId", "VaultKeyRotationVaultId", "VaultKeyRotationId");
                        });

                    b.Navigation("BaseKeyEpoch")
                        .IsRequired();

                    b.Navigation("TargetKeyEpoch")
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyRotationPreparedItem", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.VaultKeyRotation", null)
                        .WithMany("PreparedItems")
                        .HasForeignKey("OrganizationId", "VaultId", "RotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultMember", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", "Vault")
                        .WithMany("VaultMembers")
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultMemberKeyEnvelope", b =>
                {
                    b.HasOne("Palladin.Module.Vault.Domain.Vault", "Vault")
                        .WithMany("VaultMemberKeyEnvelopes")
                        .HasForeignKey("OrganizationId", "VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.Grant", b =>
                {
                    b.Navigation("AgentWrappedVaultKey");

                    b.Navigation("EncryptedReason");

                    b.Navigation("GrantEntryScopes");

                    b.Navigation("ScriptExecutionPackage");

                    b.Navigation("ScriptExecutionScopes");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.GrantEntryScope", b =>
                {
                    b.Navigation("Envelope");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.Vault", b =>
                {
                    b.Navigation("AgentVaultDiscoveryEnvelopes");

                    b.Navigation("KeyMaterialEnvelopes");

                    b.Navigation("VaultMemberKeyEnvelopes");

                    b.Navigation("VaultMembers");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultEntry", b =>
                {
                    b.Navigation("Keys");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Palladin.Module.Vault.Domain.VaultKeyRotation", b =>
                {
                    b.Navigation("PreparedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
