<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="NodaTime.Testing" Version="3.3.0" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\core\Palladin.Core.Analytics\Palladin.Core.Analytics.csproj" />
        <ProjectReference Include="..\..\src\core\Palladin.Core.Hangfire\Palladin.Core.Hangfire.csproj" />
        <ProjectReference Include="..\..\src\core\Palladin.Core.Json\Palladin.Core.Json.csproj" />
        <ProjectReference Include="..\..\src\core\Palladin.Core.Types\Palladin.Core.Types.csproj" />
        <ProjectReference Include="..\..\src\modules\Agents\Palladin.Module.Agents\Palladin.Module.Agents.csproj" />
        <ProjectReference Include="..\..\src\modules\OpenHost\Audit\Palladin.Module.Audit\Palladin.Module.Audit.csproj" />
        <ProjectReference Include="..\..\src\modules\Identity\Palladin.Module.Identity\Palladin.Module.Identity.csproj" />
        <ProjectReference Include="..\..\src\modules\OpenHost\Notification\Palladin.Module.Notification\Palladin.Module.Notification.csproj" />
        <ProjectReference Include="..\..\src\modules\OpenHost\Search\Palladin.Module.Search\Palladin.Module.Search.csproj" />
        <ProjectReference Include="..\..\src\modules\Vault\Palladin.Module.Vault\Palladin.Module.Vault.csproj" />
        <ProjectReference Include="..\..\src\modules\OpenHost\PublicAssetCatalog\Palladin.Module.PublicAssetCatalog\Palladin.Module.PublicAssetCatalog.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Fixtures\**\*.json" Link="Fixtures\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
