// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palladin.Module.Identity.Infrastructure.Persistence;

#nullable disable

namespace Palladin.Module.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbWriteContext))]
    [Migration("20260910191820_AddSharedUnlockPreference")]
    partial class AddSharedUnlockPreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palladin.Module.Identity.Domain.LoginLockout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<Instant?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("SourceIpAddresses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Instant>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("LoginLockouts");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.LoginRateLimitBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Instant>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartitionKey")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("LoginRateLimitBuckets");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OAuthConnection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("OAuthConnections");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AgentEnrolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApiKeyCreated")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MembershipVersion")
                        .IsConcurrencyToken()
                        .HasPrecision(20)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OfflineAccessPolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<long>("OfflineAccessPolicyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10)
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<int>("SeatLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<Instant>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Email");

                    b.HasIndex("OrganizationId", "RoleId");

                    b.ToTable("OrganizationInvitations");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMember", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("AuthorizationVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<Instant>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovalRequestId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("RemovalRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemovalRequestedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMemberDirectoryEntry", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganizationId", "UserId");

                    b.ToTable("OrganizationMemberDirectoryEntries");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMemberRole", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "UserId", "RoleId");

                    b.HasIndex("OrganizationId", "RoleId");

                    b.ToTable("OrganizationMemberRoles");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.PasswordCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AuthHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("AuthSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ServerHashSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("PasswordCredentials");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AuthorizationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("TokenHash");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.Role", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.TotpCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("LastUsedTimeStep")
                        .HasColumnType("bigint");

                    b.Property<string>("PendingSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Secret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("TotpCredentials");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.TotpRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TotpRecoveryCodes");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CredentialRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<byte[]>("DeviceWrapperMetadata")
                        .HasMaxLength(16384)
                        .HasColumnType("bytea");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedPrivateKeyByRecovery")
                        .HasColumnType("bytea");

                    b.Property<bool>("EntryCreated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean");

                    b.Property<string>("KdfProfileId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("MemberKeyVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("MinimumSecurityVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("MobileRegistered")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("PrivateKeyWrapRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecoverySalt")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("SharedUnlockEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long>("SharedUnlockRevision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.Property<Instant>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("WaitlistDeveloperBenefitEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("WaitlistDeveloperBenefitStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash", "Purpose");

                    b.HasIndex("UserId", "Purpose");

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeveloperBenefitEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeveloperBenefitStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeveloperBenefitUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Instant>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Instant>("TokenIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperBenefitUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TokenHash");

                    b.ToTable("WaitlistEntries");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OAuthConnection", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.User", "User")
                        .WithMany("OAuthConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationInvitation", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.Organization", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Identity.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMember", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Identity.Domain.User", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMemberDirectoryEntry", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMemberRole", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.Role", "Role")
                        .WithMany("MemberAssignments")
                        .HasForeignKey("OrganizationId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Palladin.Module.Identity.Domain.OrganizationMember", "Member")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("OrganizationId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.PasswordCredential", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.User", "User")
                        .WithOne("PasswordCredential")
                        .HasForeignKey("Palladin.Module.Identity.Domain.PasswordCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.RefreshToken", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.Role", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.TotpCredential", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.User", "User")
                        .WithOne("TotpCredential")
                        .HasForeignKey("Palladin.Module.Identity.Domain.TotpCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.TotpRecoveryCode", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.TotpCredential", "Credential")
                        .WithMany("RecoveryCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.User", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.VerificationToken", b =>
                {
                    b.HasOne("Palladin.Module.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.Organization", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.OrganizationMember", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.Role", b =>
                {
                    b.Navigation("MemberAssignments");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.TotpCredential", b =>
                {
                    b.Navigation("RecoveryCodes");
                });

            modelBuilder.Entity("Palladin.Module.Identity.Domain.User", b =>
                {
                    b.Navigation("OAuthConnections");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("PasswordCredential");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TotpCredential");
                });
#pragma warning restore 612, 618
        }
    }
}
