// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palladin.Module.Agents.Infrastructure.Persistence;

#nullable disable

namespace Palladin.Module.Agents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentsDbWriteContext))]
    [Migration("20260815093134_AddFormDiscoveryMaps")]
    partial class AddFormDiscoveryMaps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palladin.Module.Agents.Domain.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AccessEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("access_epoch");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid?>("DeactivatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by");

                    b.Property<Guid?>("DeactivationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivation_request_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Instant?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid?>("EnrolledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_by");

                    b.Property<string>("IconColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icon_color");

                    b.Property<string>("IconKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_key");

                    b.Property<Instant?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<string>("LastHostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("last_hostname");

                    b.Property<string>("LastIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_ip");

                    b.Property<Guid?>("LastUsedApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_used_api_key_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("public_key");

                    b.Property<Instant?>("ReactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reactivated_at");

                    b.Property<Guid?>("ReactivatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reactivated_by");

                    b.Property<long>("RecipientKeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("recipient_key_version");

                    b.Property<string>("SigningPublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signing_public_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeactivatedBy");

                    b.HasIndex("EnrolledBy");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.HasIndex("ReactivatedBy");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_suffix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.FormDiscoveryMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("definition_json");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("login_url");

                    b.Property<int>("MapVersion")
                        .HasColumnType("integer")
                        .HasColumnName("map_version");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_agent_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Domain", "Provider", "MapVersion")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Domain", "Provider", "Status");

                    b.ToTable("form_discovery_maps", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("agent_users", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.Agent", b =>
                {
                    b.HasOne("Palladin.Module.Agents.Domain.User", "DeactivatedByUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_agents_deactivated_by");

                    b.HasOne("Palladin.Module.Agents.Domain.User", "EnrolledByUser")
                        .WithMany()
                        .HasForeignKey("EnrolledBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_agents_enrolled_by");

                    b.HasOne("Palladin.Module.Agents.Domain.User", "ReactivatedByUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_agents_reactivated_by");

                    b.Navigation("DeactivatedByUser");

                    b.Navigation("EnrolledByUser");

                    b.Navigation("ReactivatedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
