// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palladin.Module.Agents.Infrastructure.Persistence;

#nullable disable

namespace Palladin.Module.Agents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentsDbWriteContext))]
    partial class AgentsDbWriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palladin.Module.Agents.Domain.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AccessEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("access_epoch");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<Guid?>("DeactivatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by");

                    b.Property<Guid?>("DeactivationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivation_request_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Instant?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid?>("EnrolledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolled_by");

                    b.Property<string>("IconColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icon_color");

                    b.Property<string>("IconKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_key");

                    b.Property<Instant?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<string>("LastHostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("last_hostname");

                    b.Property<string>("LastIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("last_ip");

                    b.Property<Guid?>("LastUsedApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_used_api_key_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("public_key");

                    b.Property<Instant?>("ReactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reactivated_at");

                    b.Property<Guid?>("ReactivatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reactivated_by");

                    b.Property<long>("RecipientKeyVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("recipient_key_version");

                    b.Property<string>("SigningPublicKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("signing_public_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeactivatedBy");

                    b.HasIndex("EnrolledBy");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.HasIndex("ReactivatedBy");

                    b.HasIndex("OrganizationId", "NameKey");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.AgentDisplayNameFence", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.HasKey("OrganizationId")
                        .HasName("PK_agent_display_name_fences");

                    b.ToTable("agent_display_name_fences", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.AgentPairingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialCiphertext")
                        .HasColumnType("text")
                        .HasColumnName("credential_ciphertext");

                    b.Property<string>("CredentialEphemeralPublicKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("credential_ephemeral_public_key");

                    b.Property<string>("CredentialNonce")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("credential_nonce");

                    b.Property<string>("CredentialSuite")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("credential_suite");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Hostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("public_key");

                    b.Property<string>("RequestedDisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requested_display_name");

                    b.Property<string>("RequestedType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("requested_type");

                    b.Property<string>("ReservedDisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reserved_display_name");

                    b.Property<string>("ReservedDisplayNameKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reserved_display_name_key");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("SigningPublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signing_public_key");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_agent_pairing_requests");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PublicKey");

                    b.HasIndex("OrganizationId", "ReservedDisplayNameKey")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_pairing_requests_reserved_name")
                        .HasFilter("status = 1 AND reserved_display_name_key IS NOT NULL");

                    b.HasIndex("Status", "UpdatedAt", "Id");

                    b.ToTable("agent_pairing_requests", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_suffix");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.ApiKeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeySuffix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_suffix");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_key_credentials", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.FormDiscoveryMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition_json");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_url");

                    b.Property<int>("MapVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("map_version")
                        .HasDefaultValueSql("nextval('form_discovery_map_revision_seq')");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_agent_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MapVersion")
                        .IsUnique();

                    b.HasIndex("Domain", "Provider", "Fingerprint")
                        .IsUnique();

                    b.HasIndex("Domain", "Provider", "Status", "MapVersion");

                    b.ToTable("form_discovery_maps", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("agent_users", (string)null);
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.Agent", b =>
                {
                    b.HasOne("Palladin.Module.Agents.Domain.User", "DeactivatedByUser")
                        .WithMany()
                        .HasForeignKey("DeactivatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_agents_deactivated_by");

                    b.HasOne("Palladin.Module.Agents.Domain.User", "EnrolledByUser")
                        .WithMany()
                        .HasForeignKey("EnrolledBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_agents_enrolled_by");

                    b.HasOne("Palladin.Module.Agents.Domain.User", "ReactivatedByUser")
                        .WithMany()
                        .HasForeignKey("ReactivatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_agents_reactivated_by");

                    b.Navigation("DeactivatedByUser");

                    b.Navigation("EnrolledByUser");

                    b.Navigation("ReactivatedByUser");
                });

            modelBuilder.Entity("Palladin.Module.Agents.Domain.ApiKeyCredential", b =>
                {
                    b.HasOne("Palladin.Module.Agents.Domain.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_credentials_agent");

                    b.HasOne("Palladin.Module.Agents.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_key_credentials_api_key");
                });
#pragma warning restore 612, 618
        }
    }
}
